---CASE WHEN

SELECT * FROM USERS
---burada K ve E yerine Kadýn Erkek yazalým. 
---Peki cinsiyetlerde E ve K dýþýnda veri var mý?
SELECT DISTINCT GENDER FROM USERS
---kadýn ya da erkek ya da diðerleri
SELECT 
CASE WHEN 
	GENDER ='K' THEN 'Kadýn'
	WHEN GENDER = 'E' THEN  'Erkek' ELSE GENDER END AS CINSIYETTANIM,
GENDER
FROM USERS
---kadýn ve diðerleri :)
SELECT 
CASE WHEN 
	GENDER ='K' THEN 'Kadýn'
	ELSE 'Erkek' END AS CINSIYETTANIM,
GENDER
FROM USERS

---yaþ aralýklarýna göre kategorize et
SELECT
CASE WHEN AGE BETWEEN 10 AND 30 THEN 'GENC'
WHEN AGE BETWEEN 31 AND 45 THEN 'ORTAYAS'
WHEN AGE BETWEEN 46 AND 60 THEN 'ORTAYASUSTU'
ELSE 'YASLI' END AS YASGRUBU, AGE, * 
FROM USERS
WHERE AGE = 0

---Eðer yaþ deðeri yanlýþ girilmiþ/boþ veri varsa 'BOS' yaz

SELECT
CASE WHEN AGE BETWEEN 10 AND 30 THEN 'GENC'
WHEN AGE BETWEEN 31 AND 45 THEN 'ORTAYAS'
WHEN AGE BETWEEN 46 AND 60 THEN 'ORTAYASUSTU'
WHEN AGE > 61 THEN 'YASLI'
ELSE 'BOS' END AS YASGRUBU, AGE, * 
FROM USERS

SELECT 
CASE WHEN LINETOTAL BETWEEN 10 AND 30 THEN 'AZ'
WHEN LINETOTAL BETWEEN 31 AND 50 THEN 'ORTA'
WHEN LINETOTAL BETWEEN 51 AND 99 THEN 'UST'
WHEN LINETOTAL BETWEEN 100 AND 200 THEN 'LUKS'
ELSE 'NO_INFO' 
END + ' GELIR' AS GELIRGRUPCONCAT,
LINETOTAL
FROM SALEORDERS

----SUB QUERY
SELECT * FROM SALEORDERS
WHERE BRAND = (SELECT DISTINCT BRAND FROM ITEMS WHERE BRAND='ULKER')

---Hangi müþterinin sipariþi hazýr? Hangisinin deðil?
SELECT DISTINCT STATUS_ FROM ORDERS ---MÜÞTERÝ SÝPARÝÞ BÝLGÝSÝ

SELECT * FROM USERS 
WHERE USERS.ID IN (SELECT ORDERS.USERID 
					FROM ORDERS 
					WHERE STATUS_ = '2')


---Sirapiþ Tablosunda kategorisi pil olanlarýn verisi lazým.
SELECT * FROM SALEORDERS WHERE CATEGORY3 = 'PIL' --- PÝLÝN hangi kategoride geçtiðini bulalým

--- Elimde alkalin, çinko karbon, kalem, þarjlý gibi detaylý pil çeþitleri var.
--- Detay istemiyorsam kategori3 = pil diyelim

SELECT * FROM SALEORDERS
WHERE ITEMCODE IN (SELECT ITEMCODE FROM ITEMS WHERE CATEGORY3 = 'PIL')

---kategorisi kýrtasiye olan müþteri adeti getirsin

SELECT NAMESURNAME,SUM(AMOUNT) AS ADET FROM ORDERS O 
INNER JOIN ORDERDETAILS OD ON O.ID = OD.ORDERID
INNER JOIN USERS U ON U.ID = O.USERID
WHERE AGE=85 
AND YEAR(DATE_)=2020
AND OD.ITEMID IN (SELECT ITEMID FROM ITEMS WHERE CATEGORY3='KIRTASIYE')
GROUP BY NAMESURNAME
ORDER BY ADET DESC


