--1) addres tablosunun kontrol etmek için top 100 ünü çekiniz.

SELECT TOP 100 * FROM ADDRESS -- * koymazsak error alýrýz top 100'deki hangi sütunlar?

--2)CITIES tablosuna yeni bir kayýt olarak ID,COUNTRYID VE memlektenizi ekleyin.

INSERT INTO CITIES VALUES('82','1','KIRKLARELÝ') -- 1 = TÜRKÝYE demek, ekleme yaptýðýmýz için insert kullandýk update deðil
SELECT * FROM CITIES

--3)[dbo].[USERS] tablosundaki 10 numaralý id yi kendi bilgileriniz ile update edin.

SELECT * FROM USERS WHERE ID=10

UPDATE USERS
SET USERNAME_='eceirem', PASSWORD_ = 'ucankirpi', NAMESURNAME='ECE ÝREM ÞÝÞER',EMAIL='eceiremsiser@gmail.com', GENDER='K', BIRTHDATE='09-01-2004', AGE='21'
WHERE ID=10

SELECT * FROM USERS WHERE ID=10

--4)[dbo].[SALEORDERS] tablosunda category1 i SEKERLEME OLAN KAYITLARI GETÝRÝN.

SELECT * FROM SALEORDERS WHERE CATEGORY1='SEKERLEME'

--5)[dbo].[SALEORDERS] tablosunda LINETOTALI 20.000 DEN BUYUK KAYITLARI GETIRIN.

SELECT * FROM  SALEORDERS WHERE LINETOTAL>20.000

--6)[dbo].[SALEORDERS] tablosunda haftaiçi olan kayýtlarý getirin.

SELECT * FROM SALEORDERS WHERE DAYOFWEEK_ NOT IN ('CUMARTESÝ','PAZAR') --HAFTASONU OLMAYANLARI GETÝRDÝM

--7)[dbo].[SALEORDERS] tablosunda pazar günü ve Tablet satýþlarýný getirin.

SELECT * FROM SALEORDERS WHERE CATEGORY4='TABLET' AND DAYOFWEEK_='PAZAR'

--8)[dbo].[ITEMS]tablosunda kaç tane tekin category1 vardýr.

SELECT DISTINCT CATEGORY1 FROM ITEMS --bunu yazarsam 24 gösterir ama yazmazsam toplam satýþ 28.062 gösterir çünkü tekrar önemsemez

--9)[dbo].[ITEMS]tablosundaki ürünleri unitprice a göre büyükten küçüðe sýralayýnýz.

SELECT ITEMNAME,UNITPRICE FROM ITEMS ORDER BY UNITPRICE DESC

--10)[dbo].[SALEORDERS] tablosunda þehirlere göre (SUM,COUNT,MIN,MAX,AVG) adeti getirin.

SELECT * FROM SALEORDERS

SELECT CITY, SUM(LINETOTAL) TOPLAM_SATIS, COUNT(ID) SATIÞ_ADEDI,MIN(LINETOTAL) MÝN_SATIS ,MAX(LINETOTAL) MAKS_SATIS, AVG(LINETOTAL) ORTLAMA_SATIS FROM SALEORDERS GROUP BY CITY

--11) ÜRÜN KATEGORÝLERÝNE GÖRE TOPLAM SATIÞLARý getirin.

SELECT CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4, SUM(LINETOTAL) AS TOPLAM_SATIÞ FROM SALEORDERS GROUP BY CATEGORY1, CATEGORY2, CATEGORY3,CATEGORY4

--12)order ve user tablolarýný left,right ve inner olarak þekilde birleþtiriniz.
SELECT * FROM ORDERS
SELECT * FROM USERS
SELECT * FROM ORDERS AS O LEFT JOIN USERS AS U ON O.USERID = U.ID
SELECT * FROM ORDERS AS O RIGHT JOIN USERS AS U ON O.USERID = U.ID
SELECT * FROM ORDERS AS O INNER JOIN USERS AS U ON O.USERID = U.ID

SELECT * FROM ORDERS AS O RIGHT JOIN USERS AS U ON O.USERID = U.ID WHERE O.USERID IS NULL; 
---right join yaptýðýmda daha çok sayýda satýr çýktý bu da demek oluyor ki null deðer var

SELECT * FROM ORDERS AS O LEFT JOIN USERS AS U ON O.USERID = U.ID WHERE O.USERID IS NULL; 
---burada olmaz çünkü null almaz

--13)adress ve user tablolarýný left,right ve inner olarak þekilde birleþtiriniz.

SELECT * FROM ADDRESS AS A LEFT JOIN USERS AS U ON A.USERID = U.ID ---25.051 satýr
SELECT * FROM ADDRESS AS A RIGHT JOIN USERS AS U ON A.USERID = U.ID ---24.273
SELECT * FROM ADDRESS AS A INNER JOIN USERS AS U ON A.USERID = U.ID ---24.270

--14)En fazla alýþveriþ hangi markada yapýlmýþtýr.

SELECT TOP 1 MAX(LINETOTAL) AS MAXSATIS,BRAND AS MARKA FROM SALEORDERS GROUP BY BRAND 

--15)oyuncak ANA KATEGORÝSÝNDE KATEGORÝSÝNDE, ZEKA GELISTIRICI UST KATEGORISINDE,OYUNCAKLAR ALT KATEGORISINDE EN FAZLA SATIÞ YAPAN, bebe oyuncaklarý nelerdir?

SELECT ITEMNAME, BRAND, SUM(LINETOTAL) AS TOPLAMSATIS 
FROM SALEORDERS 
WHERE 
  CATEGORY1 = 'OYUNCAK' 
  AND CATEGORY2 = 'ZEKA GELISTIRICI' 
  AND CATEGORY3 = 'OYUNCAKLAR' 
  AND CATEGORY4 = 'BEBE OYUNCAK' 
GROUP BY ITEMNAME, BRAND
ORDER BY TOPLAMSATIS DESC;

--16) TEMIZLIK KATEGORÝSÝNDEKI URUNLERIN ORTALAMA FÝYAT NEDÝR

SELECT AVG(UNITPRICE) AS ORTLAMA_ÜRÜN_FÝYATI FROM SALEORDERS WHERE CATEGORY1='TEMIZLIK'

--17) HANGÝ YAÞ GRUPLARI DAHA FAZLA ALIÞVERÝÞ YAPMIÞTIR

SELECT U.AGE AS YAÞ, COUNT(U.ID) AS KÝÞÝ_SAYISI 
FROM ORDERS AS O INNER JOIN USERS AS U ON O.USERID = U.ID 
GROUP BY AGE
ORDER BY KÝÞÝ_SAYISI DESC

--18)[dbo].[ITEMS] TABLOSUNDAKÝ TÜM CATERGORYLERÝ BÝRLEÞTÝRÝN.

---ÖNCE SÜTUN EKLE
ALTER TABLE ITEMS
ADD KATEGORI_DIZINI VARCHAR(255);

---SÜTUN ÝÇERÝÐÝNÝ KATEGORÝLERÝ EKLEYEREK DEÐERLERÝ GÜNCELLE
UPDATE ITEMS
SET KATEGORI_DIZINI = CONCAT(CATEGORY1, ' > ', CATEGORY2, ' > ', CATEGORY3, ' > ', CATEGORY4);

SELECT * FROM ITEMS;

--19)[dbo].[PAYMENTS] TABLOSUNDAKÝ APPROVECODE KOLONUNUN ILK 5 DEÐERÝNÝ AYRI BÝR KOLON OLARAK YAZIN.

ALTER TABLE PAYMENTS
ADD APPROVED_KEY VARCHAR(15);

UPDATE PAYMENTS 
SET APPROVED_KEY = SUBSTRING(APPROVECODE, 1, 5)

--20)[dbo].[PAYMENTS] TABLOSUNDAKÝ SAYISAL DEÐERLERÝ AYRI BÝR KOLON OLARAK YAZIN.

ALTER TABLE PAYMENTS
ADD APPROVED_NUMERIC_CODE VARCHAR(255);

UPDATE PAYMENTS 
SET APPROVED_NUMERIC_CODE = SUBSTRING(APPROVECODE, 6, LEN(APPROVECODE)-5)

--21)[dbo].[USERS] TABLOSUNDAKÝ PASSWORD KOLONUNU TÜM DEÐERLERÝ BÜYÜK YAZIN.

UPDATE USERS
SET PASSWORD_ = UPPER(PASSWORD_)

SELECT * FROM USERS

--22)[dbo].[USERS] TABLOSUNDAKÝ NAMESURNAME  KOLONUNUNDAKÝ SOYÝSÝMLERÝ TÜM DEÐERLERÝ KÜÇÜK YAZIN.

UPDATE USERS
SET NAMESURNAME = CONCAT(LEFT(NAMESURNAME, LEN(NAMESURNAME) - CHARINDEX(' ', REVERSE(NAMESURNAME))) , LOWER(RIGHT(NAMESURNAME, CHARINDEX(' ', REVERSE(NAMESURNAME)) - 1)))
---concat demeyi unuttuðum için name kýsýmlarý full silindi :D

SELECT * FROM USERS

--23)[dbo].[INVOICES] TABLOSUNDAKÝ DATE KOLONUNU AÞAÐIDAKÝ FORMATLARA ÇEVÝRÝN.
			--mm/dd/yyyy
			--yyyy.mm.dd
			--dd.mm.yyyy
			--yyyymmdd

SELECT CONVERT(varchar,DATE_,101)TARIH, DATE_ FROM ORDERS ---mm/dd/yyyy

SELECT CONVERT(varchar,DATE_,102)TARIH, DATE_ FROM ORDERS --yyyy.mm.dd

SELECT CONVERT(varchar,DATE_,104)TARIH, DATE_ FROM ORDERS ---dd.mm.yyyy

SELECT CONVERT(varchar,DATE_,112)TARIH, DATE_ FROM ORDERS ---yyyymmdd


--24)[dbo].[INVOICES] TABLOSUNDAKÝ DATE KOLONUNU YIL,AY,GUN,HAFTA OLARAK AYRI AYIR KOLONLARDA GÖSTERÝN.

SELECT YEAR(DATE_) AS YIL , MONTH(DATE_) AS AY , DAY(DATE_) AS GÜN, DATEPART(WEEKDAY, DATE_) AS HAFTANINGÜNÜ, DATEPART(HOUR, DATE_) AS SAAT, DATE_ FROM INVOICES

--25)[dbo].[SALEORDERS] TABLOSUNDAKÝ MONTH KOLONUNA GÖRE HANGÝ AYIN HANGÝ MEVSÝME GELDÝÐÝNÝ YAZIN.

SELECT *, 
	CASE
		WHEN MONTH_ IN ('ARALIK','OCAK','ÞUBAT') THEN 'KIÞ'
		WHEN MONTH_ IN ('MART','NÝSAN','MAYIS') THEN 'BAHAR'
		WHEN MONTH_ IN ('HAZÝRAN','TEMMUZ','AÐUSTOS') THEN 'YAZ'
		WHEN MONTH_ IN ('EYLÜL','EKÝM','KASIM') THEN 'SONBAHAR'
	ELSE ' '
  END AS SEASON
FROM SALEORDERS;


--26)[dbo].[ITEMS] TABLOSUDNAKÝ BRANDLERÝ AÞAÐIDAKÝ KURALA GÖRE YENÝ BÝR KOLON OLUÞTURUNUZ.
		--ULKER ISE YEME ICME
		--REXONA ISE KOZMATIK
		--ALGIDA ISE DONDURMA
		--NESCAFE ISE SICAKICECEK
		--BUNLARIN DIÞINDAKILER DIGER 


ALTER TABLE ITEMS
ADD YENÝKATEGORÝ VARCHAR(255)

UPDATE ITEMS
SET YENÝKATEGORÝ = 
	CASE
			WHEN BRAND = 'ULKER' THEN 'YEME ICME' 
			WHEN BRAND = 'REXONA' THEN 'KOZMATIK'
			WHEN BRAND = 'ALGIDA' THEN 'DONDURMA'
			WHEN BRAND = 'NESCAFE' THEN 'SICAKICECEK'
		ELSE 'DIGER'
	END;

SELECT * FROM ITEMS

























