---STRING ÝÞLEMLERÝ 

---Substring Fonk.

SELECT SUBSTRING(NAMESURNAME,0,2) AS SUB, NAMESURNAME
FROM USERS

SELECT SUBSTRING(BIRTHDATE,1,3) FROM USERS ---Veri tipine dikkat, date olduðu için iþlem yapýlmaz

---Charindex Fonk.
--- Z harfi hangi konumda? 
SELECT CHARINDEX('Z',NAMESURNAME,1), NAMESURNAME FROM USERS

---Concat Fonk.
select 'Ece' + ' Ýrem' + ' Þiþer' AS isim_soyisim

select CONCAT('Ece', ' ' ,'Ýrem',' ','Þiþer') AS isim_soyisim

SELECT USERNAME_ + ' ' +PASSWORD_ FROM USERS

SELECT CONCAT(USERNAME_ , ' ' ,PASSWORD_) FROM USERS

SELECT CONCAT(NAMESURNAME, '---_', GENDER) FROM USERS


---Left, Right, Len

SELECT LEFT(BIRTHDATE,4) AS YIL, BIRTHDATE 
FROM USERS


SELECT RIGHT(BIRTHDATE,5) AS YIL, BIRTHDATE 
FROM USERS

---domain hesabýný görmek
SELECT RIGHT(EMAIL,16), EMAIL FROM USERS


---þifre uzunluðunu gör
SELECT LEN(PASSWORD_), PASSWORD_ FROM USERS

----LTRIM, RTRIM

SELECT RTRIM(' - Ece - ')
SELECT lTRIM(' - Ece - ')

---Lower, Upper, Reverse
SELECT LOWER(USERNAME_), USERNAME_ FROM USERS
SELECT LOWER(USERNAME_) KUCUK, UPPER(NAMESURNAME) BUYUK, *  FROM USERS

SELECT REVERSE(PASSWORD_) AS PSW, PASSWORD_ FROM USERS

---SAYI HESABI
----Küsuratlý sayýlarý yuvarlamak isteyebiliriz.
---Yuvarlama

SELECT ROUND(TOTALPRICE, 0), TOTALPRICE FROM ORDERS ---NEREYE YAKINSA
SELECT FLOOR(TOTALPRICE), TOTALPRICE FROM ORDERS ---ALTA
SELECT CEILING(TOTALPRICE), TOTALPRICE FROM ORDERS ---ÜSTE


---TARÝHSEL ÝÞLEMLER
--- yilaygun 20250718 format deðiþtirmek (mm/dd/yyyy) olabilir

SELECT CONVERT(varchar,DATE_,101)TARIH, DATE_ FROM ORDERS
---101 bir koddur. her id farklý þekilde dönüþtürme yapar

---yyyy.mm.dd
SELECT CONVERT(varchar,DATE_,102)TARIH, DATE_ FROM ORDERS

---dd.mm.yyyy
SELECT CONVERT(varchar,DATE_,104)TARIH, DATE_ FROM ORDERS

--- dd mon yyyy (ayý string yazdý)
SELECT CONVERT(varchar,DATE_,106)TARIH, DATE_ FROM ORDERS

--- hh:mm:ss (saat dakika salise)
SELECT CONVERT(varchar,DATE_,108)TARIH, DATE_ FROM ORDERS

---dd/mm/yy
SELECT CONVERT(varchar,DATE_,3)TARIH, DATE_ FROM ORDERS



---DATEDIFF
SELECT GETDATE()
 
SELECT MAX(DATE_) FROM ORDERS

SELECT DATEDIFF(DAY,MAX(DATE_),GETDATE()) AS FARK, 
MAX(DATE_) AS MAXDATE, 
GETDATE() AS BUGUN 
FROM ORDERS

SELECT * FROM ORDERS 
WHERE CONVERT(varchar, DATE_, 112) = CONVERT(varchar,GETDATE(),112)-50587



---DATEADD 
SELECT DATEADD(DAY,1,GETDATE()) AS YENI, * FROM ORDERS

SELECT DATEADD(DAY,1,DATE_) AS YENI, * FROM ORDERS

---DATEPART tarih içinden birini çek

---tarihleri ayýralým
SELECT DATEPART(DAY,DATE_)GÜN,DATEPART(MONTH,DATE_) AY ,DATEPART(YEAR,DATE_) YIL, DATE_ FROM ORDERS


---yaz aylarýndaki toplam ciro
SELECT SUM(TOTALPRICE) AS YAZ_CIROSUNUN_TOPLAMI
FROM ORDERS
WHERE MONTH(DATE_) IN (6, 7, 8) AND YEAR(DATE_)=2019

